sudo: required
language: generic

services:
        - docker

before_install:
  - docker build -t amitv08/docker_repo -f Dockerfile.dev .

script:
  - docker run -e CI=true amitv08/docker_repo npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker_app"
  env: "DockerApp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-189139619842"
  bucket_path: "docker_app"
  on:
    branch:master    
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: 
      secure: "$AWS_SECRET_KEY"
